elasticsearch:
    host: 172.28.155.227:9200
    ##username: elastic
    ##password: ydT7m5qAZUmBuIyZlKVO

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgre
        username: user
        password: 1234
        driver-class-name: org.postgresql.Driver

    jpa:
        show-sql: true

    rabbitmq:
        host: 172.28.155.227
        port: 5672
        username: guest
        password: guest
