elasticsearch:
    host: 127.0.0.1:9200
    ##username: elastic
    ##password: ydT7m5qAZUmBuIyZlKVO

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: user
        password: 8426
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true

    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest

sentry:
  dsn: https://67cf3b0561759dd4252f6e7f94b3934c@o4511794346000384.ingest.us.sentry.io/4511794349015045
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true
  # Enable sending logs to Sentry
  logs:
    enabled: true
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  # Set profile-session-sample-rate to 1.0 to profile 100% of profile sessions.
  profile-session-sample-rate: 1.0
  # Set profile-lifecycle to trace to automatically start and stop
  # profiling when a transaction starts and finishes.
  profile-lifecycle: TRACE